### ISSUE TITLE
Refactor Code into Separate JavaScript and CSS Files

### ISSUE THREAD

**Issue by aditya-bhaumik** [GameSphere-MultiPlayer/Formation-Absent#11]
## Description:

The current project embeds all JavaScript and CSS code within the HTML file. This proposal suggests separating these concerns into distinct files for improved maintainability and accessibility.

## Points:

Separating JavaScript and CSS into game.js and styles.css files respectively enhances code organization.
Clear separation of concerns improves code readability, aiding both current developers and potential contributors in understanding and navigating the project.

## Program contributing in:

- [x] GSSoc'24
- [x]  I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Formation-Absent/issues/new?assignees=&labels=&projects=&template=new_features_request.yml&title=%5BNew+Feature%5D%3A+) of this project.

**Comment by aditya-bhaumik** [comment]
@Durgesh4993 can you please assign me this issue

**Comment by roy7077** [comment]
@aditya-bhaumik I am assigning this issue to you. Please go ahead
