### ISSUE TITLE
[Documentation Bug]: Missing git pull command in contributing.md file.

### ISSUE THREAD

**Issue by Amruta7203** [GameSphere-MultiPlayer/Formation-Absent#18]
### Describe the bug ✍️

There is a missing git pull command in the contributing.md file after git add upstream command. 

![image](https://github.com/GameSphere-MultiPlayer/Formation-Absent/assets/116087736/4042082b-359c-4448-b5b4-28b2d6d887ee)

### Provide step by step information reproduce the bug 📄

Adding this command is important for contribution to ensure that the changes are made in the updated code.

![image](https://github.com/GameSphere-MultiPlayer/Formation-Absent/assets/116087736/8313925f-e0c3-449d-93d0-2778fe1f6f52)

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
