### ISSUE TITLE
[New Feature]: Adding a footer about copyrights and contact us section

### ISSUE THREAD

**Issue by karthickkumarsm** [GameSphere-MultiPlayer/Formation-Absent#22]
### 🎮 feature Request

Adding a footer about copyrights and contact us will be more useful when someone tries to contact

### Point down the features

my feature will have a good looking footer with contact us section includes various social media links

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Shravani246** [comment]
please assign me this project.I can do it

**Comment by roy7077** [comment]
@Shravani246 go Ahead , I am assigning this issue to you.

**Comment by karthickkumarsm** [comment]
Bro I created the issue and messaged in LinkedIn to assign this to me

> @Shravani246 go Ahead , I am assigning this issue to you.

**Comment by karthickkumarsm** [comment]
@roy7077

**Comment by Durgesh4993** [comment]
@Shravani246 Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created separate channals for all projects...

Thank you :)
