### ISSUE TITLE
[Documentation Updatation]:  Upadate readme.md

### ISSUE THREAD

**Issue by Abhigna-arsam** [GameSphere-MultiPlayer/Formation-Absent#27]
### Describe the bug ✍️

The current README lacks visual appeal and comprehensive information, making it challenging for users to quickly grasp the project's technology stack, features, and structure.

### Provide step by step information reproduce the bug 📄

I propose updating the README by adding tech stack logos to visually represent the technologies used, add some description of the project , and including a table of contents for easy navigation.

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Abhigna-arsam** [comment]
please assign this issue to me

**Comment by roy7077** [comment]
@Abhigna-arsam Go ahead,
