### ISSUE TITLE
[Bug]: Footer icons anchor tag is not working

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [GameSphere-MultiPlayer/Formation-Absent#31]
### Give a brief about the bug ✍️

![image](https://github.com/GameSphere-MultiPlayer/Formation-Absent/assets/125277258/3bdacca7-a5ab-4f80-9e2c-09476796726f)

### What is the expected behavior? 🤔

it should be redirected to some social media accounts

### Provide step by step information reproduce the bug 📄

it should be redirected to some social media accounts

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by RamakrushnaBiswal** [comment]
hi @roy7077 can you assign it to me

**Comment by roy7077** [comment]
@RamakrushnaBiswal  assigning this issue to you, go ahead

**Comment by RamakrushnaBiswal** [comment]
hi @roy7077 looks like not been assigned yet assign 1st then merge the PR

**Comment by RamakrushnaBiswal** [comment]
issue solved #33
