### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository 

### ISSUE THREAD

**Issue by suhanipaliwal** [GameSphere-MultiPlayer/Formation-Absent#7]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by Durgesh4993** [comment]
![image](https://github.com/GameSphere-MultiPlayer/Formation-Absent/assets/98798977/680783e9-dbb4-4362-8dee-49926796670d)

**Comment by Durgesh4993** [comment]
We already have CONTRIBUTING.md File Please raise any other issue, i'll assign you

If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
