### ISSUE TITLE
[New Feature]: ADDING FAVICON ICON 

### ISSUE THREAD

**Issue by solanki505** [GameSphere-MultiPlayer/Formation-Absent#8]
### 🎮 feature Request

feature logic and basic description
adding favicon icon to web page 
![Screenshot 2024-05-12 182353](https://github.com/GameSphere-MultiPlayer/Formation-Absent/assets/158484284/6f958829-c1b3-4095-8139-c77f2b6b1bd4)

### Point down the features

feature points
adding icon 
I want to work on this issue under GSSOC'24

### Select program in which you are contributing

GSSoC24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by PrishaThapar06** [comment]
Hi there,  I'm reaching out to express my interest in contributing to the project through GSSOC'24. I'm eager to gain valuable experience and make meaningful contributions to the project. Please assign this issue to me. Thank you.

**Comment by Durgesh4993** [comment]
If you have any doubt you can directly send message on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)
